month(january).
month(february).
month(march).
month(april).
month(may).
month(june).
month(july).
month(augest).
month(september).
month(october).
month(november).
month(december).

next_month(february,january).
next_month(march,february).
next_month(april,march).
next_month(may,april).
next_month(june,may).
next_month(july,june).
next_month(augest,july).
next_month(september,augest).
next_month(october,september).
next_month(november,october).
next_month(december,november).
next_month(january,december).

days_of(31,january).
days_of(28,february).
days_of(31,march).
days_of(30,april).
days_of(31,may).
days_of(30,june).
days_of(31,july).
days_of(31,augest).
days_of(30,september).
days_of(31,october).
days_of(30,november).
days_of(31,december).
